package com.zhoumj.model;

import com.zhoumj.enumtype.AuditInfoStatusEnum;
import java.util.Date;

public class AuditInfo {
    /**
     *  ID,所属表字段为O2O.TBL_O2O_AUDITINFO.ID
     */
    private Long id;

    /**
     *  审核人,所属表字段为O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_ID
     */
    private Long bossOperatorId;

    /**
     *  审核人姓名,所属表字段为O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_NAME
     */
    private String bossOperatorName;

    /**
     *  被审核的供应商ID,所属表字段为O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_ID
     */
    private Long auditCustomerId;

    /**
     *  被审核的供应商姓名,所属表字段为O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_NAME
     */
    private String auditCustomerName;

    /**
     *  审核状态,所属表字段为O2O.TBL_O2O_AUDITINFO.AUDIT_STATUS
     */
    private AuditInfoStatusEnum auditStatus;

    /**
     *  审核原因说明,所属表字段为O2O.TBL_O2O_AUDITINFO.AUDIT_DETAIL
     */
    private String auditDetail;

    /**
     *  审核创建日期,所属表字段为O2O.TBL_O2O_AUDITINFO.AUDIT_CREATEDATE
     */
    private Date createDate;

    /**
     *  审核更新日期,所属表字段为O2O.TBL_O2O_AUDITINFO.AUDIT_UPDATEDATE
     */
    private Date updateDate;

    /**
     *  null,所属表字段为O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_CODE
     */
    private String skbAuditCode;

    /**
     *  null,所属表字段为O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_MESSAGE
     */
    private String skbAuditMessage;

    /**
     *  null,所属表字段为O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_CODE
     */
    private String skbSearchCode;

    /**
     *  null,所属表字段为O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_MESSAGE
     */
    private String skbSearchMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.ID
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.ID
     *
     * @param id the value for O2O.TBL_O2O_AUDITINFO.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_ID
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_ID
     *
     * @mbggenerated
     */
    public Long getBossOperatorId() {
        return bossOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_ID
     *
     * @param bossOperatorId the value for O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_ID
     *
     * @mbggenerated
     */
    public void setBossOperatorId(Long bossOperatorId) {
        this.bossOperatorId = bossOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_NAME
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getBossOperatorName() {
        return bossOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_NAME
     *
     * @param bossOperatorName the value for O2O.TBL_O2O_AUDITINFO.BOSS_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setBossOperatorName(String bossOperatorName) {
        this.bossOperatorName = bossOperatorName == null ? null : bossOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_ID
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_ID
     *
     * @mbggenerated
     */
    public Long getAuditCustomerId() {
        return auditCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_ID
     *
     * @param auditCustomerId the value for O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_ID
     *
     * @mbggenerated
     */
    public void setAuditCustomerId(Long auditCustomerId) {
        this.auditCustomerId = auditCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_NAME
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_NAME
     *
     * @mbggenerated
     */
    public String getAuditCustomerName() {
        return auditCustomerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_NAME
     *
     * @param auditCustomerName the value for O2O.TBL_O2O_AUDITINFO.AUDIT_CUSTOMER_NAME
     *
     * @mbggenerated
     */
    public void setAuditCustomerName(String auditCustomerName) {
        this.auditCustomerName = auditCustomerName == null ? null : auditCustomerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_STATUS
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.AUDIT_STATUS
     *
     * @mbggenerated
     */
    public AuditInfoStatusEnum getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_STATUS
     *
     * @param auditStatus the value for O2O.TBL_O2O_AUDITINFO.AUDIT_STATUS
     *
     * @mbggenerated
     */
    public void setAuditStatus(AuditInfoStatusEnum auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_DETAIL
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.AUDIT_DETAIL
     *
     * @mbggenerated
     */
    public String getAuditDetail() {
        return auditDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_DETAIL
     *
     * @param auditDetail the value for O2O.TBL_O2O_AUDITINFO.AUDIT_DETAIL
     *
     * @mbggenerated
     */
    public void setAuditDetail(String auditDetail) {
        this.auditDetail = auditDetail == null ? null : auditDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_CREATEDATE
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.AUDIT_CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_CREATEDATE
     *
     * @param createDate the value for O2O.TBL_O2O_AUDITINFO.AUDIT_CREATEDATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_UPDATEDATE
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.AUDIT_UPDATEDATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.AUDIT_UPDATEDATE
     *
     * @param updateDate the value for O2O.TBL_O2O_AUDITINFO.AUDIT_UPDATEDATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_CODE
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_CODE
     *
     * @mbggenerated
     */
    public String getSkbAuditCode() {
        return skbAuditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_CODE
     *
     * @param skbAuditCode the value for O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_CODE
     *
     * @mbggenerated
     */
    public void setSkbAuditCode(String skbAuditCode) {
        this.skbAuditCode = skbAuditCode == null ? null : skbAuditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_MESSAGE
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_MESSAGE
     *
     * @mbggenerated
     */
    public String getSkbAuditMessage() {
        return skbAuditMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_MESSAGE
     *
     * @param skbAuditMessage the value for O2O.TBL_O2O_AUDITINFO.SKB_AUDIT_MESSAGE
     *
     * @mbggenerated
     */
    public void setSkbAuditMessage(String skbAuditMessage) {
        this.skbAuditMessage = skbAuditMessage == null ? null : skbAuditMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_CODE
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_CODE
     *
     * @mbggenerated
     */
    public String getSkbSearchCode() {
        return skbSearchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_CODE
     *
     * @param skbSearchCode the value for O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_CODE
     *
     * @mbggenerated
     */
    public void setSkbSearchCode(String skbSearchCode) {
        this.skbSearchCode = skbSearchCode == null ? null : skbSearchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_MESSAGE
     *
     * @return the value of O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_MESSAGE
     *
     * @mbggenerated
     */
    public String getSkbSearchMessage() {
        return skbSearchMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_MESSAGE
     *
     * @param skbSearchMessage the value for O2O.TBL_O2O_AUDITINFO.SKB_SEARCH_MESSAGE
     *
     * @mbggenerated
     */
    public void setSkbSearchMessage(String skbSearchMessage) {
        this.skbSearchMessage = skbSearchMessage == null ? null : skbSearchMessage.trim();
    }
}